name: Robot Framework CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1. 소스 코드 체크아웃 (v4 사용)
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. 파이썬 환경 설정 (v5 사용)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. 의존성 및 브라우저 설치
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          rfbrowser init

      # 4. 로봇 프레임워크 테스트 실행
      - name: Run Robot Framework Tests
        run: |
          robot -d results tests/

      # 5. 결과 파일 업로드 (v4 사용 - 에러 해결의 핵심)
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-results-${{ github.run_id }}
<<<<<<<< HEAD:workflows/ci.yml
          path: results/
========
          path: results/
>>>>>>>> 78136f6caccd5782f6bab8a90e40b9f5f8abe6ff:workflows/robot.ci.yml
